# Dockerfile untuk Core 1
FROM nginx:latest
COPY /image /usr/share/nginx/html/images
EXPOSE 80


# docker volume create images_vol
# docker run -d -v images_vol:/usr/share/nginx/html/images --name webserver nginx
