version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: 'cc_image'
      MYSQL_USER: 'novin'
      MYSQL_PASSWORD: 'novin'
      MYSQL_ROOT_PASSWORD: 'password_root'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: flask_api
    restart: always
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    ports:
      - "5001:5000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
